# This is a basic workflow to help you get started with Actions
name: Create a comment on new issues

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
   types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
